import { Container, dag, Directory } from "@dagger.io/dagger";
import { GenericLayer, mkRPM, sourceFileIn, unindent } from "../../lib";

const GID_ONEPASSWORD = 1500;
const GID_ONEPASSWORDCLI = 1600;
const GID_ONEPASSWORDMCP = 1700;

const BROWSER_SUPPORT_PATH = "/usr/lib/1Password/1Password-BrowserSupport";
const MCP_PATH = "/usr/lib/1Password/1password-mcp";
const CLI_PATH = "/usr/bin/op";

const sourceFile = sourceFileIn(import.meta.dirname);

export class OnepasswordLayer extends GenericLayer {
    name = "onepassword";

    async build(buildContainer: Container): Promise<Directory> {
        const rpms = buildContainer
            .withNewFile("/etc/yum.repos.d/1password.repo", sourceFile("1password.repo"))
            .withNewFile("/etc/pki/rpm-gpg/RPM-GPG-KEY-1password", sourceFile("1password.asc"))
            .withExec(["rpm", "--import", "/etc/pki/rpm-gpg/RPM-GPG-KEY-1password"])
            .withDirectory("/tmp/rpms", dag.directory())
            .withExec(["bash", "-euo", "pipefail", "-c",
                "dnf download -y --arch=$(uname -m) --from-repo=1password --destdir=/tmp/rpms 1password 1password-cli"])
            .withDirectory("/rpms", dag.directory())
            .withExec(["bash", "-euo", "pipefail", "-c", unindent`
                # dnf download verifies nothing by itself
                rpm -K /tmp/rpms/*.rpm

                mv /tmp/rpms/1password-cli-*.rpm /rpms/cli.rpm
                mv /tmp/rpms/1password-[0-9]*.rpm /rpms/app.rpm
            `]);

        const metaVersion = rpms.withExec(["rpm", "-qp", "--qf", "%{VERSION}", "/rpms/app.rpm"]).stdout();
        const metaCliVersion = rpms.withExec(["rpm", "-qp", "--qf", "%{VERSION}", "/rpms/cli.rpm"]).stdout();
        const metaLicense = rpms.withExec(["rpm", "-qp", "--qf", "%{LICENSE}", "/rpms/app.rpm"]).stdout();
        const metaSummary = rpms.withExec(["rpm", "-qp", "--qf", "%{SUMMARY}", "/rpms/app.rpm"]).stdout();
        const metaUrl = rpms.withExec(["rpm", "-qp", "--qf", "%{URL}", "/rpms/app.rpm"]).stdout();
        // rpmlib() capabilities and the scriptlet interpreter are re-generated by rpmbuild, so they are dropped here.
        const metaRequires = rpms.withExec(["bash", "-euo", "pipefail", "-c", unindent`
                {
                    rpm -qp --qf '[%{REQUIRENAME}\n]' "/rpms/app.rpm"
                    rpm -qp --qf '[%{REQUIRENAME}\n]' "/rpms/cli.rpm"
                } | grep -vE '^(rpmlib\\(|/bin/sh$)' | sort -u
            `]).stdout();
        const metaPost = rpms.withExec(["bash", "-euo", "pipefail", "-c", unindent`
                rpm -qp --qf '%{POSTIN}' "/rpms/app.rpm" > /tmp/post-app.sh
                rpm -qp --qf '%{POSTIN}' "/rpms/cli.rpm" > /tmp/post-cli.sh

                sed -i 's|/opt/1Password|/usr/lib/1Password|g' /tmp/post-app.sh
                sed -i 's|/opt/1Password|/usr/lib/1Password|g' /tmp/post-cli.sh

                echo set -e
                echo "("
                cat /tmp/post-app.sh
                echo -e "\n)"
                echo "("
                cat /tmp/post-cli.sh
                echo -e "\n)"
            `]).stdout();

        const contents = rpms
            .withDirectory("/out", dag.directory())
            .withExec(["bash", "-euo", "pipefail", "-c", "cat /rpms/app.rpm | rpm2archive - | tar -xz -C /out"])
            .withExec(["bash", "-euo", "pipefail", "-c", "cat /rpms/cli.rpm | rpm2archive - | tar -xz -C /out"])
            .withExec(["mv", "/out/opt/1Password", "/out/usr/lib/1Password"])
            .withExec(["rmdir", "/out/opt"])
            .withExec(["rm", "-rf", "/out/usr/lib/.build-id"])
            .directory("/out")
            .withNewFile(
                "usr/lib/sysusers.d/onepassword.conf",
                `g onepassword ${GID_ONEPASSWORD}\n`,
            )
            .withNewFile(
                "usr/lib/sysusers.d/onepassword-cli.conf",
                `g onepassword-cli ${GID_ONEPASSWORDCLI}\n`,
            )
            .withNewFile(
                "usr/lib/sysusers.d/onepassword-mcp.conf",
                `g onepassword-mcp ${GID_ONEPASSWORDMCP}\n`,
            )
            .withNewFile(
                "usr/lib/tmpfiles.d/onepassword.conf",
                unindent`
                    d  /var/opt/1Password  -  -  -  -  -
                `,
            )
            .withNewFile(
                "usr/lib/systemd/system/var-opt-1Password.mount",
                unindent`
                    [Unit]
                    Description=Bind mount 1Password from /usr/lib to /opt
                    DefaultDependencies=no
                    Conflicts=umount.target
                    After=systmed-tmpfiles-setup.service

                    [Mount]
                    What=/usr/lib/1Password
                    Where=/var/opt/1Password
                    Options=bind

                    [Install]
                    WantedBy=local-fs.target
                `,
            );

        return dag.directory().withFile(
            "1password.rpm",
            await mkRPM(buildContainer)(
                {
                    name: "1password-repack",
                    version: (await metaVersion).trim(),
                    license: (await metaLicense).trim(),
                    summary: (await metaSummary).trim(),
                    url: (await metaUrl).trim(),
                    description: (await metaSummary).trim(),
                    // The CLI is folded in, so claim what it used to provide.
                    provides: [`1password = ${(await metaVersion).trim()}`, `1password-cli = ${(await metaCliVersion).trim()}`],
                    requires: (await metaRequires).split("\n").filter((it) => it.trim()),
                    post: await metaPost,
                },
                contents,
            ),
        );
    }

    installScript = `
        mkdir -p /var/opt /var/usrlocal

        dnf install -y ./1password.rpm

        # The scriptlet has already applied these, but against groups it created with
        # groupadd, which do not exist on the running system. Re-point them at the GIDs
        # pinned in sysusers.d. chgrp clears the setgid bit, so it has to be re-set after.
        chgrp ${GID_ONEPASSWORD} ${BROWSER_SUPPORT_PATH}
        chmod g+s ${BROWSER_SUPPORT_PATH}

        chgrp ${GID_ONEPASSWORDMCP} ${MCP_PATH}
        chmod g+s ${MCP_PATH}

        chgrp ${GID_ONEPASSWORDCLI} ${CLI_PATH}
        chmod g+s ${CLI_PATH}

        # The patched script creates these as symlinks to /usr/lib
        ln -sf /opt/1Password/1password /usr/bin/1password
        ln -sf /opt/1Password/1password-mcp /usr/bin/1password-mcp

        systemctl enable var-opt-1Password.mount
    `;
}
